#name, main, version and api are required
name: DeathNote
main: keopiwauyu\DeathNote\MainClass
version: 0.0.1
api: 4.0.0
depend:
- PiggyCustomEnchants

load: POSTWORLD
author: 커피와 우유
description: death note showing the new API
website: https://github.com/keopiwauyu/DeathNote
commands:
  example:
    description: Example command
    usage: "/example"
    permission: DeathNote.command.example
permissions:
  DeathNote.command.example:
    description: "Allows the user to run the example command"
    default: true
